name: website
description: ratajczyk.me website

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  flutter_email_sender: ^2.2.1
  draggable_scrollbar: ^0.0.4

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Raleway-Light
      fonts:
        - asset: fonts/Raleway-Light.ttf
        - asset: fonts/Raleway-LightItalic.ttf
          style: italic
    - family: Raleway-SemiBold
      fonts:
        - asset: fonts/Raleway-SemiBold.ttf
        - asset: fonts/Raleway-SemiBoldItalic.ttf
          style: italic

  uses-material-design: true

  assets:
    - assets/Uglyface.png
    - assets/